/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.gottaeat.domain.fraud;
@org.apache.avro.specific.AvroGenerated
public enum PaymentType implements org.apache.avro.generic.GenericEnumSymbol<PaymentType> {
  CREDITCARD, PAYPAL, GOOGLECHECKOUT, BITCOIN, WIRED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"PaymentType\",\"namespace\":\"com.gottaeat.domain.fraud\",\"symbols\":[\"CREDITCARD\",\"PAYPAL\",\"GOOGLECHECKOUT\",\"BITCOIN\",\"WIRED\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
