/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.gottaeat.domain.fraud.scoring.fraudlabs;

@org.apache.avro.specific.AvroGenerated
public interface OrderScreenProtocol {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"OrderScreenProtocol\",\"namespace\":\"com.gottaeat.domain.fraud.scoring.fraudlabs\",\"types\":[{\"type\":\"enum\",\"name\":\"PaymentType\",\"symbols\":[\"CREDITCARD\",\"PAYPAL\",\"GOOGLECHECKOUT\",\"BITCOIN\",\"WIRED\"]},{\"type\":\"record\",\"name\":\"Address\",\"fields\":[{\"name\":\"address\",\"type\":\"string\"},{\"name\":\"city\",\"type\":\"string\"},{\"name\":\"state\",\"type\":\"string\"},{\"name\":\"country\",\"type\":\"string\"},{\"name\":\"postalCode\",\"type\":\"string\"}]},{\"type\":\"record\",\"name\":\"Transaction\",\"fields\":[{\"name\":\"ip\",\"type\":\"string\"},{\"name\":\"lastName\",\"type\":\"string\"},{\"name\":\"firstName\",\"type\":\"string\"},{\"name\":\"billingAddress\",\"type\":\"Address\"},{\"name\":\"shipToLastName\",\"type\":\"string\"},{\"name\":\"shipToFirstName\",\"type\":\"string\"},{\"name\":\"shippingAddress\",\"type\":\"Address\"},{\"name\":\"email\",\"type\":\"string\"},{\"name\":\"phoneNumber\",\"type\":\"string\"},{\"name\":\"paymentMode\",\"type\":\"PaymentType\"},{\"name\":\"amount\",\"type\":\"float\"}]}],\"messages\":{}}");

  @SuppressWarnings("all")
  public interface Callback extends OrderScreenProtocol {
    public static final org.apache.avro.Protocol PROTOCOL = com.gottaeat.domain.fraud.scoring.fraudlabs.OrderScreenProtocol.PROTOCOL;
  }
}