/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.gottaeat.domain.fraud.fraudlabs;

@org.apache.avro.specific.AvroGenerated
public interface FraudLabsProtocol {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"FraudLabsProtocol\",\"namespace\":\"com.gottaeat.domain.fraud.fraudlabs\",\"types\":[{\"type\":\"record\",\"name\":\"LatLon\",\"namespace\":\"com.gottaeat.domain.geography\",\"fields\":[{\"name\":\"latitude\",\"type\":\"double\"},{\"name\":\"longitude\",\"type\":\"double\"}]},{\"type\":\"record\",\"name\":\"Address\",\"namespace\":\"com.gottaeat.domain.geography\",\"fields\":[{\"name\":\"street\",\"type\":\"string\"},{\"name\":\"city\",\"type\":\"string\"},{\"name\":\"state\",\"type\":\"string\"},{\"name\":\"country\",\"type\":\"string\"},{\"name\":\"zip\",\"type\":\"string\"}]},{\"type\":\"record\",\"name\":\"GeoEncodedAddress\",\"namespace\":\"com.gottaeat.domain.geography\",\"fields\":[{\"name\":\"address\",\"type\":\"Address\"},{\"name\":\"geo\",\"type\":[\"null\",\"LatLon\"]}]},{\"type\":\"enum\",\"name\":\"PaymentType\",\"symbols\":[\"CREDITCARD\",\"PAYPAL\",\"GOOGLECHECKOUT\",\"BITCOIN\",\"WIRED\"]},{\"type\":\"record\",\"name\":\"Transaction\",\"fields\":[{\"name\":\"ip\",\"type\":\"string\"},{\"name\":\"lastName\",\"type\":\"string\"},{\"name\":\"firstName\",\"type\":\"string\"},{\"name\":\"billingAddress\",\"type\":\"com.gottaeat.domain.geography.Address\"},{\"name\":\"shipToLastName\",\"type\":\"string\"},{\"name\":\"shipToFirstName\",\"type\":\"string\"},{\"name\":\"shippingAddress\",\"type\":\"com.gottaeat.domain.geography.Address\"},{\"name\":\"email\",\"type\":\"string\"},{\"name\":\"phoneNumber\",\"type\":\"string\"},{\"name\":\"paymentMode\",\"type\":\"PaymentType\"},{\"name\":\"amount\",\"type\":\"float\"}]}],\"messages\":{}}");

  @SuppressWarnings("all")
  public interface Callback extends FraudLabsProtocol {
    public static final org.apache.avro.Protocol PROTOCOL = com.gottaeat.domain.fraud.fraudlabs.FraudLabsProtocol.PROTOCOL;
  }
}