/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.gottaeat.domain.fraud.fraudlabs;
@org.apache.avro.specific.AvroGenerated
public enum ScoringStatus implements org.apache.avro.generic.GenericEnumSymbol<ScoringStatus> {
  APPROVE, REJECT, REVIEW  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"ScoringStatus\",\"namespace\":\"com.gottaeat.domain.fraud.fraudlabs\",\"symbols\":[\"APPROVE\",\"REJECT\",\"REVIEW\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
