/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.gottaeat.domain.customer;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class CustomerDetails extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 7663976383328562000L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"CustomerDetails\",\"namespace\":\"com.gottaeat.domain.customer\",\"fields\":[{\"name\":\"lastName\",\"type\":\"string\"},{\"name\":\"firstName\",\"type\":\"string\"},{\"name\":\"billingAddress\",\"type\":{\"type\":\"record\",\"name\":\"Address\",\"namespace\":\"com.gottaeat.domain.geography\",\"fields\":[{\"name\":\"street\",\"type\":\"string\"},{\"name\":\"city\",\"type\":\"string\"},{\"name\":\"state\",\"type\":\"string\"},{\"name\":\"country\",\"type\":\"string\"},{\"name\":\"zip\",\"type\":\"string\"}]}},{\"name\":\"email\",\"type\":\"string\"},{\"name\":\"phoneNumber\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<CustomerDetails> ENCODER =
      new BinaryMessageEncoder<CustomerDetails>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<CustomerDetails> DECODER =
      new BinaryMessageDecoder<CustomerDetails>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<CustomerDetails> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<CustomerDetails> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<CustomerDetails> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<CustomerDetails>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this CustomerDetails to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a CustomerDetails from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a CustomerDetails instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static CustomerDetails fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence lastName;
  @Deprecated public java.lang.CharSequence firstName;
  @Deprecated public com.gottaeat.domain.geography.Address billingAddress;
  @Deprecated public java.lang.CharSequence email;
  @Deprecated public java.lang.CharSequence phoneNumber;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public CustomerDetails() {}

  /**
   * All-args constructor.
   * @param lastName The new value for lastName
   * @param firstName The new value for firstName
   * @param billingAddress The new value for billingAddress
   * @param email The new value for email
   * @param phoneNumber The new value for phoneNumber
   */
  public CustomerDetails(java.lang.CharSequence lastName, java.lang.CharSequence firstName, com.gottaeat.domain.geography.Address billingAddress, java.lang.CharSequence email, java.lang.CharSequence phoneNumber) {
    this.lastName = lastName;
    this.firstName = firstName;
    this.billingAddress = billingAddress;
    this.email = email;
    this.phoneNumber = phoneNumber;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return lastName;
    case 1: return firstName;
    case 2: return billingAddress;
    case 3: return email;
    case 4: return phoneNumber;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: lastName = (java.lang.CharSequence)value$; break;
    case 1: firstName = (java.lang.CharSequence)value$; break;
    case 2: billingAddress = (com.gottaeat.domain.geography.Address)value$; break;
    case 3: email = (java.lang.CharSequence)value$; break;
    case 4: phoneNumber = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'lastName' field.
   * @return The value of the 'lastName' field.
   */
  public java.lang.CharSequence getLastName() {
    return lastName;
  }


  /**
   * Sets the value of the 'lastName' field.
   * @param value the value to set.
   */
  public void setLastName(java.lang.CharSequence value) {
    this.lastName = value;
  }

  /**
   * Gets the value of the 'firstName' field.
   * @return The value of the 'firstName' field.
   */
  public java.lang.CharSequence getFirstName() {
    return firstName;
  }


  /**
   * Sets the value of the 'firstName' field.
   * @param value the value to set.
   */
  public void setFirstName(java.lang.CharSequence value) {
    this.firstName = value;
  }

  /**
   * Gets the value of the 'billingAddress' field.
   * @return The value of the 'billingAddress' field.
   */
  public com.gottaeat.domain.geography.Address getBillingAddress() {
    return billingAddress;
  }


  /**
   * Sets the value of the 'billingAddress' field.
   * @param value the value to set.
   */
  public void setBillingAddress(com.gottaeat.domain.geography.Address value) {
    this.billingAddress = value;
  }

  /**
   * Gets the value of the 'email' field.
   * @return The value of the 'email' field.
   */
  public java.lang.CharSequence getEmail() {
    return email;
  }


  /**
   * Sets the value of the 'email' field.
   * @param value the value to set.
   */
  public void setEmail(java.lang.CharSequence value) {
    this.email = value;
  }

  /**
   * Gets the value of the 'phoneNumber' field.
   * @return The value of the 'phoneNumber' field.
   */
  public java.lang.CharSequence getPhoneNumber() {
    return phoneNumber;
  }


  /**
   * Sets the value of the 'phoneNumber' field.
   * @param value the value to set.
   */
  public void setPhoneNumber(java.lang.CharSequence value) {
    this.phoneNumber = value;
  }

  /**
   * Creates a new CustomerDetails RecordBuilder.
   * @return A new CustomerDetails RecordBuilder
   */
  public static com.gottaeat.domain.customer.CustomerDetails.Builder newBuilder() {
    return new com.gottaeat.domain.customer.CustomerDetails.Builder();
  }

  /**
   * Creates a new CustomerDetails RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new CustomerDetails RecordBuilder
   */
  public static com.gottaeat.domain.customer.CustomerDetails.Builder newBuilder(com.gottaeat.domain.customer.CustomerDetails.Builder other) {
    if (other == null) {
      return new com.gottaeat.domain.customer.CustomerDetails.Builder();
    } else {
      return new com.gottaeat.domain.customer.CustomerDetails.Builder(other);
    }
  }

  /**
   * Creates a new CustomerDetails RecordBuilder by copying an existing CustomerDetails instance.
   * @param other The existing instance to copy.
   * @return A new CustomerDetails RecordBuilder
   */
  public static com.gottaeat.domain.customer.CustomerDetails.Builder newBuilder(com.gottaeat.domain.customer.CustomerDetails other) {
    if (other == null) {
      return new com.gottaeat.domain.customer.CustomerDetails.Builder();
    } else {
      return new com.gottaeat.domain.customer.CustomerDetails.Builder(other);
    }
  }

  /**
   * RecordBuilder for CustomerDetails instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<CustomerDetails>
    implements org.apache.avro.data.RecordBuilder<CustomerDetails> {

    private java.lang.CharSequence lastName;
    private java.lang.CharSequence firstName;
    private com.gottaeat.domain.geography.Address billingAddress;
    private com.gottaeat.domain.geography.Address.Builder billingAddressBuilder;
    private java.lang.CharSequence email;
    private java.lang.CharSequence phoneNumber;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.gottaeat.domain.customer.CustomerDetails.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.lastName)) {
        this.lastName = data().deepCopy(fields()[0].schema(), other.lastName);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.firstName)) {
        this.firstName = data().deepCopy(fields()[1].schema(), other.firstName);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.billingAddress)) {
        this.billingAddress = data().deepCopy(fields()[2].schema(), other.billingAddress);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (other.hasBillingAddressBuilder()) {
        this.billingAddressBuilder = com.gottaeat.domain.geography.Address.newBuilder(other.getBillingAddressBuilder());
      }
      if (isValidValue(fields()[3], other.email)) {
        this.email = data().deepCopy(fields()[3].schema(), other.email);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.phoneNumber)) {
        this.phoneNumber = data().deepCopy(fields()[4].schema(), other.phoneNumber);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
    }

    /**
     * Creates a Builder by copying an existing CustomerDetails instance
     * @param other The existing instance to copy.
     */
    private Builder(com.gottaeat.domain.customer.CustomerDetails other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.lastName)) {
        this.lastName = data().deepCopy(fields()[0].schema(), other.lastName);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.firstName)) {
        this.firstName = data().deepCopy(fields()[1].schema(), other.firstName);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.billingAddress)) {
        this.billingAddress = data().deepCopy(fields()[2].schema(), other.billingAddress);
        fieldSetFlags()[2] = true;
      }
      this.billingAddressBuilder = null;
      if (isValidValue(fields()[3], other.email)) {
        this.email = data().deepCopy(fields()[3].schema(), other.email);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.phoneNumber)) {
        this.phoneNumber = data().deepCopy(fields()[4].schema(), other.phoneNumber);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'lastName' field.
      * @return The value.
      */
    public java.lang.CharSequence getLastName() {
      return lastName;
    }


    /**
      * Sets the value of the 'lastName' field.
      * @param value The value of 'lastName'.
      * @return This builder.
      */
    public com.gottaeat.domain.customer.CustomerDetails.Builder setLastName(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.lastName = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'lastName' field has been set.
      * @return True if the 'lastName' field has been set, false otherwise.
      */
    public boolean hasLastName() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'lastName' field.
      * @return This builder.
      */
    public com.gottaeat.domain.customer.CustomerDetails.Builder clearLastName() {
      lastName = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'firstName' field.
      * @return The value.
      */
    public java.lang.CharSequence getFirstName() {
      return firstName;
    }


    /**
      * Sets the value of the 'firstName' field.
      * @param value The value of 'firstName'.
      * @return This builder.
      */
    public com.gottaeat.domain.customer.CustomerDetails.Builder setFirstName(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.firstName = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'firstName' field has been set.
      * @return True if the 'firstName' field has been set, false otherwise.
      */
    public boolean hasFirstName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'firstName' field.
      * @return This builder.
      */
    public com.gottaeat.domain.customer.CustomerDetails.Builder clearFirstName() {
      firstName = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'billingAddress' field.
      * @return The value.
      */
    public com.gottaeat.domain.geography.Address getBillingAddress() {
      return billingAddress;
    }


    /**
      * Sets the value of the 'billingAddress' field.
      * @param value The value of 'billingAddress'.
      * @return This builder.
      */
    public com.gottaeat.domain.customer.CustomerDetails.Builder setBillingAddress(com.gottaeat.domain.geography.Address value) {
      validate(fields()[2], value);
      this.billingAddressBuilder = null;
      this.billingAddress = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'billingAddress' field has been set.
      * @return True if the 'billingAddress' field has been set, false otherwise.
      */
    public boolean hasBillingAddress() {
      return fieldSetFlags()[2];
    }

    /**
     * Gets the Builder instance for the 'billingAddress' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public com.gottaeat.domain.geography.Address.Builder getBillingAddressBuilder() {
      if (billingAddressBuilder == null) {
        if (hasBillingAddress()) {
          setBillingAddressBuilder(com.gottaeat.domain.geography.Address.newBuilder(billingAddress));
        } else {
          setBillingAddressBuilder(com.gottaeat.domain.geography.Address.newBuilder());
        }
      }
      return billingAddressBuilder;
    }

    /**
     * Sets the Builder instance for the 'billingAddress' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */
    public com.gottaeat.domain.customer.CustomerDetails.Builder setBillingAddressBuilder(com.gottaeat.domain.geography.Address.Builder value) {
      clearBillingAddress();
      billingAddressBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'billingAddress' field has an active Builder instance
     * @return True if the 'billingAddress' field has an active Builder instance
     */
    public boolean hasBillingAddressBuilder() {
      return billingAddressBuilder != null;
    }

    /**
      * Clears the value of the 'billingAddress' field.
      * @return This builder.
      */
    public com.gottaeat.domain.customer.CustomerDetails.Builder clearBillingAddress() {
      billingAddress = null;
      billingAddressBuilder = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'email' field.
      * @return The value.
      */
    public java.lang.CharSequence getEmail() {
      return email;
    }


    /**
      * Sets the value of the 'email' field.
      * @param value The value of 'email'.
      * @return This builder.
      */
    public com.gottaeat.domain.customer.CustomerDetails.Builder setEmail(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.email = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'email' field has been set.
      * @return True if the 'email' field has been set, false otherwise.
      */
    public boolean hasEmail() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'email' field.
      * @return This builder.
      */
    public com.gottaeat.domain.customer.CustomerDetails.Builder clearEmail() {
      email = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'phoneNumber' field.
      * @return The value.
      */
    public java.lang.CharSequence getPhoneNumber() {
      return phoneNumber;
    }


    /**
      * Sets the value of the 'phoneNumber' field.
      * @param value The value of 'phoneNumber'.
      * @return This builder.
      */
    public com.gottaeat.domain.customer.CustomerDetails.Builder setPhoneNumber(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.phoneNumber = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'phoneNumber' field has been set.
      * @return True if the 'phoneNumber' field has been set, false otherwise.
      */
    public boolean hasPhoneNumber() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'phoneNumber' field.
      * @return This builder.
      */
    public com.gottaeat.domain.customer.CustomerDetails.Builder clearPhoneNumber() {
      phoneNumber = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public CustomerDetails build() {
      try {
        CustomerDetails record = new CustomerDetails();
        record.lastName = fieldSetFlags()[0] ? this.lastName : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.firstName = fieldSetFlags()[1] ? this.firstName : (java.lang.CharSequence) defaultValue(fields()[1]);
        if (billingAddressBuilder != null) {
          try {
            record.billingAddress = this.billingAddressBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("billingAddress"));
            throw e;
          }
        } else {
          record.billingAddress = fieldSetFlags()[2] ? this.billingAddress : (com.gottaeat.domain.geography.Address) defaultValue(fields()[2]);
        }
        record.email = fieldSetFlags()[3] ? this.email : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.phoneNumber = fieldSetFlags()[4] ? this.phoneNumber : (java.lang.CharSequence) defaultValue(fields()[4]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<CustomerDetails>
    WRITER$ = (org.apache.avro.io.DatumWriter<CustomerDetails>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<CustomerDetails>
    READER$ = (org.apache.avro.io.DatumReader<CustomerDetails>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.lastName);

    out.writeString(this.firstName);

    this.billingAddress.customEncode(out);

    out.writeString(this.email);

    out.writeString(this.phoneNumber);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.lastName = in.readString(this.lastName instanceof Utf8 ? (Utf8)this.lastName : null);

      this.firstName = in.readString(this.firstName instanceof Utf8 ? (Utf8)this.firstName : null);

      if (this.billingAddress == null) {
        this.billingAddress = new com.gottaeat.domain.geography.Address();
      }
      this.billingAddress.customDecode(in);

      this.email = in.readString(this.email instanceof Utf8 ? (Utf8)this.email : null);

      this.phoneNumber = in.readString(this.phoneNumber instanceof Utf8 ? (Utf8)this.phoneNumber : null);

    } else {
      for (int i = 0; i < 5; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.lastName = in.readString(this.lastName instanceof Utf8 ? (Utf8)this.lastName : null);
          break;

        case 1:
          this.firstName = in.readString(this.firstName instanceof Utf8 ? (Utf8)this.firstName : null);
          break;

        case 2:
          if (this.billingAddress == null) {
            this.billingAddress = new com.gottaeat.domain.geography.Address();
          }
          this.billingAddress.customDecode(in);
          break;

        case 3:
          this.email = in.readString(this.email instanceof Utf8 ? (Utf8)this.email : null);
          break;

        case 4:
          this.phoneNumber = in.readString(this.phoneNumber instanceof Utf8 ? (Utf8)this.phoneNumber : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










