/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.gottaeat.domain.user;

@org.apache.avro.specific.AvroGenerated
public interface UserProtocol {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"UserProtocol\",\"namespace\":\"com.gottaeat.domain.user\",\"types\":[{\"type\":\"record\",\"name\":\"LatLon\",\"namespace\":\"com.gottaeat.domain.geography\",\"fields\":[{\"name\":\"latitude\",\"type\":\"double\"},{\"name\":\"longitude\",\"type\":\"double\"}]},{\"type\":\"record\",\"name\":\"Address\",\"namespace\":\"com.gottaeat.domain.geography\",\"fields\":[{\"name\":\"street\",\"type\":\"string\"},{\"name\":\"city\",\"type\":\"string\"},{\"name\":\"state\",\"type\":\"string\"},{\"name\":\"country\",\"type\":\"string\"},{\"name\":\"zip\",\"type\":\"string\"}]},{\"type\":\"record\",\"name\":\"GeoEncodedAddress\",\"namespace\":\"com.gottaeat.domain.geography\",\"fields\":[{\"name\":\"address\",\"type\":\"Address\"},{\"name\":\"geo\",\"type\":[\"null\",\"LatLon\"]}]},{\"type\":\"record\",\"name\":\"DeviceInfo\",\"fields\":[{\"name\":\"registeredUserId\",\"type\":\"int\"},{\"name\":\"location\",\"type\":[\"null\",\"com.gottaeat.domain.geography.LatLon\"]},{\"name\":\"globalIPv4\",\"type\":[\"null\",\"string\"]},{\"name\":\"globalIPv6\",\"type\":[\"null\",\"string\"]},{\"name\":\"deviceId\",\"type\":[\"null\",\"string\"]}]}],\"messages\":{}}");

  @SuppressWarnings("all")
  public interface Callback extends UserProtocol {
    public static final org.apache.avro.Protocol PROTOCOL = com.gottaeat.domain.user.UserProtocol.PROTOCOL;
  }
}