className: com.gottaeat.dao.customer.CustomerDetailsLookup
tenant: gottaeat
namespace: payments
name: customer-details-lookup
inputs:
- persistent://gottaeat/
output: persistent://gottaeat/
userConfig:
  - dbUrl: 
  - dbUser:
  - dbPass:
  - dbDriverClass: 

##################################
# Processing 
##################################
autoAck: true
logTopic: persistent://gottaeat/dao/customer-details-lookup-log
processingGuarantees: ATLEAST_ONCE
retainOrdering: false
timeoutMs: 30000
subName: customer-details-lookup-sub
cleanupSubscription: true

##################################
# Function instance resources
##################################
CPU: 2.0
disk: 50000
ram: 200000000
# parallelism: 3

##################################
# Security 
##################################
# clientAuthParams:
# clientAuthPlugin:
# hostnameVerificationEnabled: false
# tlsAllowInsecure:
# tlsTrustCertPath:
# useTls: 
