className: com.gottaeat.services.fraud.scoring.fraudlabs.FraudScoringService
tenant: gottaeat
namespace: payments
name: fraud-scoring-service
inputs:
- persistent://gottaeat/
output: persistent://gottaeat/
userConfig:
  - apiKey: YOUR_KEY 

##################################
# Processing 
##################################
autoAck: true
logTopic: persistent://gottaeat/services/fraud-scoring-service-log
processingGuarantees: ATLEAST_ONCE
retainOrdering: false
timeoutMs: 30000
subName: fraud-scoring-service-sub
cleanupSubscription: true

##################################
# Function instance resources
##################################
CPU: 2.0
disk: 50000
ram: 200000000
# parallelism: 3

##################################
# Security 
##################################
# clientAuthParams:
# clientAuthPlugin:
# hostnameVerificationEnabled: false
# tlsAllowInsecure:
# tlsTrustCertPath:
# useTls: 
