#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

FROM scylladb/scylla

# Add CQL queries to be run upon boot
COPY schemas/*.cql /docker-entrypoint-initdb.d/

COPY wrapper.sh /wrapper.sh

RUN chmod a+x /wrapper.sh

ENTRYPOINT ["/wrapper.sh"]

EXPOSE 9042