version: '2'

services:
  vault:
    image: vault
    hostname: vault.gottaeat.com
    container_name: vault
    ports:
      - "8200:8200"
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=myroot
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
      - VAULT_ADDR=http://0.0.0.0:8200
    cap_add:
      - IPC_LOCK

  mysql_database:
    image: pia/gotta-eat-db:latest
    hostname: db.gottaeat.com
    container_name: database
    ports:
      - "3306:3306"
      
  ignite:
    image: pia/gotta-eat-datagrid:latest
    container_name: datagrid
    ports:
      - "11211:11211"
      - "47100:47100"
      - "47500:47500"
      - "49112:49112"
    environment:
      - IGNITE_VERSION=2.9.0
    
  pulsar:
    depends_on:
      - mysql_database
    image: pia/gotta-eat:latest
    hostname: pulsar.gottaeat.com
    container_name: pulsar
    ports:
      - "8080:8080"
      - "6650:6650"
